---
abstract: "simple policy prohibiting the use of 'use lib'"
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-Policy-logicLAB-ProhibitUseLib
provides:
  Perl::Critic::Policy::logicLAB::ProhibitUseLib:
    file: lib/Perl/Critic/Policy/logicLAB/ProhibitUseLib.pm
    version: 0.02
requires:
  Perl::Critic: 0
  Perl::Critic::Utils: 0
  Readonly: 0
  Test::More: 0
  Test::Perl::Critic: 0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/PCPMPUL#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/PCPMPUL
  ProjectWiki: http://logiclab.jira.com/wiki/display/PCPMPUL/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Critic-logicLAB-Prohibit-UseLib
  homepage: http://logiclab.jira.com/wiki/display/PCPMPUL/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/PCPMPUL
version: 0.02
